In [1]:
import pandas as pd 
import numpy as np

In [2]:
db = pd.read_excel("temp_benchmark_data.xlsx")
db = db.iloc[21:,:]

db.head()

,SrNo,Question Name,Problem Description,Difficulty,LeetCode Link,Entry Point,Unnamed: 6
21,22,Course Schedule,There are a total of numCourses courses you ha...,Medium,"class Solution:\n def canFinish(self, numCo...","class Solution:\n def canFinish(self, numCo...",NaN
22,23,Snakes and Ladders,You are given an n x n integer matrix board wh...,Medium,from collections import deque\n\nclass Solutio...,class Solution:\n def snakesAndLadders(self...,NaN
23,24,Word Ladder,A transformation sequence from word beginWord ...,Hard,from collections import deque\n\nclass Solutio...,"class Solution:\n def ladderLength(self, be...",NaN
24,25,Find Minimum in Rotated Sorted Array,Suppose an array of length n sorted in ascendi...,Medium,"class Solution:\n def findMin(self, nums: L...","class Solution:\n def findMin(self, nums: L...",NaN
25,26,Search a 2D Matrix,You are given an m x n integer matrix matrix w...,Medium,"class Solution:\n def searchMatrix(self, ma...","class Solution:\n def searchMatrix(self, ma...",NaN

In [3]:
columns = ["meta_data","topic" , "difficulty", "question", "problem_description" , "entry_point"]
dataset = pd.DataFrame(columns = columns)
dataset.head()

Empty DataFrame
Columns: [meta_data, topic, difficulty, question, problem_description, entry_point]
Index: []

In [4]:
def topic():
    
    topics = [ "Array" , "Greedy" , "Dynamic Programming" , "Backtracking", "Divide and Conquer" , "DFS" , "BFS" , "Linked Lists" , "Two Pointers" , "Sliding Window", "Binary Trees" , 
              "Bit manipulation" , "Sorting" , "Mathematical Reasoning" , "Graph" ,"Binary Search" , "Matrix"]
    for i in range(len(topics)):
        print(f"{i}: {topics[i]}")
    print("Enter the topic index:")
    n = input()
    n = n.split(" ")
    return [topics[int(i)] for i in n]

In [5]:
def metaDataGen(index : int):
    meta = {}
    entities = db.iloc[index, :]
    meta["index"] = entities[0]
    meta["question name"] = entities[1]
    meta["difficulty"] = entities[3]
    meta["entry point"] = entities[5]
    meta["topic"] = topic()
    return meta

In [6]:
for i in range(db.shape[0]):
    entities = db.iloc[i, :]
    print(entities[1])
    data = metaDataGen(i)   
    print(data)
    row_data = pd.Series({
        columns[0]: str(data),  # Store full dict as a string
        columns[1]: str(data.get("topic", None)),  # Assign topic safely
        columns[2]: data.get("difficulty", None),  # Assign difficulty safely
        columns[3]: data.get("question name", None),  # Assign question name safely
        columns[4]: entities[2],  # Ensure correct column name
        columns[5]: data.get("entry point", None)  # Assign entry point safely
    })
    print(row_data)
    dataset.loc[i] = row_data

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

Course Schedule
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 22, 'question name': 'Course Schedule', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:', 'topic': ['DFS', 'BFS', 'Graph']}
meta_data              {'index': 22, 'question name': 'Course Schedul...
topic                                            ['DFS', 'BFS', 'Graph']
difficulty                                                        Medium
question                                                 Course Schedule
problem_description    There are a total of numCourses courses you ha...
entry_point            class Solution:\n    def canFinish(self, numCo...
dtype: object
Snakes and Ladders
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 23, 'question name': 'Snakes and Ladders', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def snakesAndLadders(self, board: List[List[int]]) -> int:', 'topic': ['DFS', 'BFS', 'Graph']}
meta_data              {'index': 23, 'question name': 'Snakes and Lad...
topic                                            ['DFS', 'BFS', 'Graph']
difficulty                                                        Medium
question                                              Snakes and Ladders
problem_description    You are given an n x n integer matrix board wh...
entry_point            class Solution:\n    def snakesAndLadders(self...
dtype: object
Word Ladder
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 24, 'question name': 'Word Ladder', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def ladderLength(self, beginWord: str, endWord: str, wordList: list[str]) -> int:', 'topic': ['Array', 'BFS', 'Matrix']}
meta_data              {'index': 24, 'question name': 'Word Ladder', ...
topic                                         ['Array', 'BFS', 'Matrix']
difficulty                                                          Hard
question                                                     Word Ladder
problem_description    A transformation sequence from word beginWord ...
entry_point            class Solution:\n    def ladderLength(self, be...
dtype: object
Find Minimum in Rotated Sorted Array
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 25, 'question name': 'Find Minimum in Rotated Sorted Array', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def findMin(self, nums: List[int]) -> int:', 'topic': ['BFS']}
meta_data              {'index': 25, 'question name': 'Find Minimum i...
topic                                                            ['BFS']
difficulty                                                        Medium
question                            Find Minimum in Rotated Sorted Array
problem_description    Suppose an array of length n sorted in ascendi...
entry_point            class Solution:\n    def findMin(self, nums: L...
dtype: object
Search a 2D Matrix
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 26, 'question name': 'Search a 2D Matrix', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:', 'topic': ['Array', 'Binary Search']}
meta_data              {'index': 26, 'question name': 'Search a 2D Ma...
topic                                         ['Array', 'Binary Search']
difficulty                                                        Medium
question                                              Search a 2D Matrix
problem_description    You are given an m x n integer matrix matrix w...
entry_point            class Solution:\n    def searchMatrix(self, ma...
dtype: object
Median of Two Sorted Arrays
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 27, 'question name': 'Median of Two Sorted Arrays', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:', 'topic': ['Array', 'Binary Search', 'Matrix']}
meta_data              {'index': 27, 'question name': 'Median of Two ...
topic                               ['Array', 'Binary Search', 'Matrix']
difficulty                                                          Hard
question                                     Median of Two Sorted Arrays
problem_description    Given two sorted arrays nums1 and nums2 of siz...
entry_point            class Solution:\n    def findMedianSortedArray...
dtype: object
Find Peak Element
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 28, 'question name': 'Find Peak Element', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def findPeakElement(self, nums: List[int]) -> int:', 'topic': ['Array', 'Binary Search']}
meta_data              {'index': 28, 'question name': 'Find Peak Elem...
topic                                         ['Array', 'Binary Search']
difficulty                                                        Medium
question                                               Find Peak Element
problem_description    A peak element is an element that is strictly ...
entry_point            class Solution:\n    def findPeakElement(self,...
dtype: object
Container With Most Water
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 29, 'question name': 'Container With Most Water', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def maxArea(self, height: List[int]) -> int:', 'topic': ['Array', 'Two Pointers', 'Greedy']}
meta_data              {'index': 29, 'question name': 'Container With...
topic                                ['Array', 'Two Pointers', 'Greedy']
difficulty                                                        Medium
question                                       Container With Most Water
problem_description    You are given an integer array height of lengt...
entry_point            class Solution:\n    def maxArea(self, height:...
dtype: object
Three Sum
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 30, 'question name': 'Three Sum', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def threeSum(self, nums: List[int]) -> List[List[int]]:        ', 'topic': ['Array', 'Two Pointers', 'Sorting']}
meta_data              {'index': 30, 'question name': 'Three Sum', 'd...
topic                               ['Array', 'Two Pointers', 'Sorting']
difficulty                                                        Medium
question                                                       Three Sum
problem_description    Given an integer array nums, return all the tr...
entry_point            class Solution:\n    def threeSum(self, nums: ...
dtype: object
Remove Duplicates from Sorted Array II
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 31, 'question name': 'Remove Duplicates from Sorted Array II', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def removeDuplicates(self, nums: List[int]) -> int:', 'topic': ['Array', 'Two Pointers']}
meta_data              {'index': 31, 'question name': 'Remove Duplica...
topic                                          ['Array', 'Two Pointers']
difficulty                                                        Medium
question                          Remove Duplicates from Sorted Array II
problem_description    Given an integer array nums sorted in non-decr...
entry_point            class Solution:\n    def removeDuplicates(self...
dtype: object
Trapping Rain Water
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 32, 'question name': 'Trapping Rain Water', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def trap(self, height: List[int]) -> int:', 'topic': ['Array', 'Two Pointers', 'Dynamic Programming']}
meta_data              {'index': 32, 'question name': 'Trapping Rain ...
topic                   ['Array', 'Two Pointers', 'Dynamic Programming']
difficulty                                                          Hard
question                                             Trapping Rain Water
problem_description    Given n non-negative integers representing an ...
entry_point            class Solution:\n    def trap(self, height: Li...
dtype: object
Longest Substring Without Repeating Characters
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 33, 'question name': 'Longest Substring Without Repeating Characters', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:', 'topic': ['Sliding Window']}
meta_data              {'index': 33, 'question name': 'Longest Substr...
topic                                                 ['Sliding Window']
difficulty                                                        Medium
question                  Longest Substring Without Repeating Characters
problem_description    Given a string s, find the length of the longe...
entry_point            class Solution:\n    def lengthOfLongestSubstr...
dtype: object
Minimum Window Substring
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 34, 'question name': 'Minimum Window Substring', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def minWindow(self, s: str, t: str) -> str:', 'topic': ['Sliding Window']}
meta_data              {'index': 34, 'question name': 'Minimum Window...
topic                                                 ['Sliding Window']
difficulty                                                          Hard
question                                        Minimum Window Substring
problem_description    Given two strings s and t of lengths m and n r...
entry_point            class Solution:\n    def minWindow(self, s: st...
dtype: object
Sliding Window Maximum
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 35, 'question name': 'Sliding Window Maximum', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:', 'topic': ['Array', 'Sliding Window']}
meta_data              {'index': 35, 'question name': 'Sliding Window...
topic                                        ['Array', 'Sliding Window']
difficulty                                                          Hard
question                                          Sliding Window Maximum
problem_description    You are given an array of integers nums, there...
entry_point            class Solution:\n    def maxSlidingWindow(self...
dtype: object
Permutation in String
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 36, 'question name': 'Permutation in String', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def checkInclusion(self, s1: str, s2: str) -> bool:', 'topic': ['Two Pointers', 'Sliding Window']}
meta_data              {'index': 36, 'question name': 'Permutation in...
topic                                 ['Two Pointers', 'Sliding Window']
difficulty                                                        Medium
question                                           Permutation in String
problem_description    Given two strings s1 and s2, return true if s2...
entry_point            class Solution:\n    def checkInclusion(self, ...
dtype: object
Reverse Bits
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 37, 'question name': 'Reverse Bits', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def reverseBits(self, n: int) -> int:', 'topic': ['Divide and Conquer', 'Bit manipulation']}
meta_data              {'index': 37, 'question name': 'Reverse Bits',...
topic                         ['Divide and Conquer', 'Bit manipulation']
difficulty                                                        Medium
question                                                    Reverse Bits
problem_description    Reverse bits of a given 32 bits unsigned integ...
entry_point            class Solution:\n    def reverseBits(self, n: ...
dtype: object
Maximum XOR of Two Numbers in an Array
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 38, 'question name': 'Maximum XOR of Two Numbers in an Array', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def findMaximumXOR(self, nums: List[int]) -> int:', 'topic': ['Array', 'Bit manipulation']}
meta_data              {'index': 38, 'question name': 'Maximum XOR of...
topic                                      ['Array', 'Bit manipulation']
difficulty                                                        Medium
question                          Maximum XOR of Two Numbers in an Array
problem_description    Given an integer array nums, return the maximu...
entry_point            class Solution:\n    def findMaximumXOR(self, ...
dtype: object
Merge K Sorted Lists
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 39, 'question name': 'Merge K Sorted Lists', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:', 'topic': ['Linked Lists', 'Divide and Conquer']}
meta_data              {'index': 39, 'question name': 'Merge K Sorted...
topic                             ['Linked Lists', 'Divide and Conquer']
difficulty                                                          Hard
question                                            Merge K Sorted Lists
problem_description    You are given an array of k linked-lists lists...
entry_point            class Solution:\n    def mergeKLists(self, lis...
dtype: object
Reverse Nodes in k-Group
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 40, 'question name': 'Reverse Nodes in k-Group', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def reverseKGroup(self, head: Optional[ListNode], k: int) -> Optional[ListNode]:', 'topic': ['Linked Lists']}
meta_data              {'index': 40, 'question name': 'Reverse Nodes ...
topic                                                   ['Linked Lists']
difficulty                                                          Hard
question                                        Reverse Nodes in k-Group
problem_description    Given the head of a linked list, reverse the n...
entry_point            class Solution:\n    def reverseKGroup(self, h...
dtype: object
Flatten Binary Tree to Linked List
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 41, 'question name': 'Flatten Binary Tree to Linked List', 'difficulty': 'Medium', 'entry point': 'class Solution:\n    def flatten(self, root: Optional[TreeNode]) -> None:\n        """\n        Do not return anything, modify root in-place instead.\n        """', 'topic': ['Linked Lists', 'Binary Search']}
meta_data              {'index': 41, 'question name': 'Flatten Binary...
topic                                  ['Linked Lists', 'Binary Search']
difficulty                                                        Medium
question                              Flatten Binary Tree to Linked List
problem_description    Given the root of a binary tree, flatten the t...
entry_point            class Solution:\n    def flatten(self, root: O...
dtype: object
Binary Tree Maximum Path Sum
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 42, 'question name': 'Binary Tree Maximum Path Sum', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def maxPathSum(self, root: Optional[TreeNode]) -> int:', 'topic': ['Binary Trees', 'Dynamic Programming', 'DFS']}
meta_data              {'index': 42, 'question name': 'Binary Tree Ma...
topic                     ['Binary Trees', 'Dynamic Programming', 'DFS']
difficulty                                                          Hard
question                                    Binary Tree Maximum Path Sum
problem_description    A path in a binary tree is a sequence of nodes...
entry_point            class Solution:\n    def maxPathSum(self, root...
dtype: object
Binary Tree Cameras
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 43, 'question name': 'Binary Tree Cameras', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def minCameraCover(self, root: Optional[TreeNode]) -> int:', 'topic': ['Dynamic Programming', 'Binary Trees', 'DFS']}
meta_data              {'index': 43, 'question name': 'Binary Tree Ca...
topic                     ['Dynamic Programming', 'Binary Trees', 'DFS']
difficulty                                                          Hard
question                                             Binary Tree Cameras
problem_description    You are given the root of a binary tree. We in...
entry_point            class Solution:\n    def minCameraCover(self, ...
dtype: object
Vertical Order Traversal of a Binary Tree
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(entities[1])
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["index"] = entities[0]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["question name"] = entities[1]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["difficulty"] = entities[3]
C:\Users\megha\AppData\Local\Temp\ipykernel_10376\1913336115.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  meta["entry point"] = entities[5]

{'index': 44, 'question name': 'Vertical Order Traversal of a Binary Tree', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def verticalTraversal(self, root: Optional[TreeNode]) -> List[List[int]]:', 'topic': ['DFS', 'BFS', 'Sorting', 'Binary Trees']}
meta_data              {'index': 44, 'question name': 'Vertical Order...
topic                          ['DFS', 'BFS', 'Sorting', 'Binary Trees']
difficulty                                                          Hard
question                       Vertical Order Traversal of a Binary Tree
problem_description    Given the root of a binary tree, calculate the...
entry_point            class Solution:\n    def verticalTraversal(sel...
dtype: object
Recover a Tree from PreOrder Traversal
0: Array
1: Greedy
2: Dynamic Programming
3: Backtracking
4: Divide and Conquer
5: DFS
6: BFS
7: Linked Lists
8: Two Pointers
9: Sliding Window
10: Binary Trees
11: Bit manipulation
12: Sorting
13: Mathematical Reasoning
14: Graph
15: Binary Search
16: Matrix
Enter the topic index:
{'index': 45, 'question name': 'Recover a Tree from PreOrder Traversal', 'difficulty': 'Hard', 'entry point': 'class Solution:\n    def recoverFromPreorder(self, traversal: str) -> Optional[TreeNode]:', 'topic': ['Binary Trees', 'DFS']}
meta_data              {'index': 45, 'question name': 'Recover a Tree...
topic                                            ['Binary Trees', 'DFS']
difficulty                                                          Hard
question                          Recover a Tree from PreOrder Traversal
problem_description    We run a preorder depth-first search (DFS) on ...
entry_point            class Solution:\n    def recoverFromPreorder(s...
dtype: object

C:\Users\megha\AppData\Local\Temp\ipykernel_10376\4272580348.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  columns[4]: entities[2],  # Ensure correct column name

In [7]:
dataset

,meta_data,topic,difficulty,question,problem_description,entry_point
0,"{'index': 22, 'question name': 'Course Schedul...","['DFS', 'BFS', 'Graph']",Medium,Course Schedule,There are a total of numCourses courses you ha...,"class Solution:\n def canFinish(self, numCo..."
1,"{'index': 23, 'question name': 'Snakes and Lad...","['DFS', 'BFS', 'Graph']",Medium,Snakes and Ladders,You are given an n x n integer matrix board wh...,class Solution:\n def snakesAndLadders(self...
2,"{'index': 24, 'question name': 'Word Ladder', ...","['Array', 'BFS', 'Matrix']",Hard,Word Ladder,A transformation sequence from word beginWord ...,"class Solution:\n def ladderLength(self, be..."
3,"{'index': 25, 'question name': 'Find Minimum i...",['BFS'],Medium,Find Minimum in Rotated Sorted Array,Suppose an array of length n sorted in ascendi...,"class Solution:\n def findMin(self, nums: L..."
4,"{'index': 26, 'question name': 'Search a 2D Ma...","['Array', 'Binary Search']",Medium,Search a 2D Matrix,You are given an m x n integer matrix matrix w...,"class Solution:\n def searchMatrix(self, ma..."
5,"{'index': 27, 'question name': 'Median of Two ...","['Array', 'Binary Search', 'Matrix']",Hard,Median of Two Sorted Arrays,Given two sorted arrays nums1 and nums2 of siz...,class Solution:\n def findMedianSortedArray...
6,"{'index': 28, 'question name': 'Find Peak Elem...","['Array', 'Binary Search']",Medium,Find Peak Element,A peak element is an element that is strictly ...,"class Solution:\n def findPeakElement(self,..."
7,"{'index': 29, 'question name': 'Container With...","['Array', 'Two Pointers', 'Greedy']",Medium,Container With Most Water,You are given an integer array height of lengt...,"class Solution:\n def maxArea(self, height:..."
8,"{'index': 30, 'question name': 'Three Sum', 'd...","['Array', 'Two Pointers', 'Sorting']",Medium,Three Sum,"Given an integer array nums, return all the tr...","class Solution:\n def threeSum(self, nums: ..."
9,"{'index': 31, 'question name': 'Remove Duplica...","['Array', 'Two Pointers']",Medium,Remove Duplicates from Sorted Array II,Given an integer array nums sorted in non-decr...,class Solution:\n def removeDuplicates(self...
10,"{'index': 32, 'question name': 'Trapping Rain ...","['Array', 'Two Pointers', 'Dynamic Programming']",Hard,Trapping Rain Water,Given n non-negative integers representing an ...,"class Solution:\n def trap(self, height: Li..."
11,"{'index': 33, 'question name': 'Longest Substr...",['Sliding Window'],Medium,Longest Substring Without Repeating Characters,"Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...
12,"{'index': 34, 'question name': 'Minimum Window...",['Sliding Window'],Hard,Minimum Window Substring,Given two strings s and t of lengths m and n r...,"class Solution:\n def minWindow(self, s: st..."
13,"{'index': 35, 'question name': 'Sliding Window...","['Array', 'Sliding Window']",Hard,Sliding Window Maximum,"You are given an array of integers nums, there...",class Solution:\n def maxSlidingWindow(self...
14,"{'index': 36, 'question name': 'Permutation in...","['Two Pointers', 'Sliding Window']",Medium,Permutation in String,"Given two strings s1 and s2, return true if s2...","class Solution:\n def checkInclusion(self, ..."
15,"{'index': 37, 'question name': 'Reverse Bits',...","['Divide and Conquer', 'Bit manipulation']",Medium,Reverse Bits,Reverse bits of a given 32 bits unsigned integ...,"class Solution:\n def reverseBits(self, n: ..."
16,"{'index': 38, 'question name': 'Maximum XOR of...","['Array', 'Bit manipulation']",Medium,Maximum XOR of Two Numbers in an Array,"Given an integer array nums, return the maximu...","class Solution:\n def findMaximumXOR(self, ..."
17,"{'index': 39, 'question name': 'Merge K Sorted...","['Linked Lists', 'Divide and Conquer']",Hard,Merge K Sorted Lists,You are given an array of k linked-lists lists...,"class Solution:\n def mergeKLists(self, lis..."
18,"{'index': 40, 'question name': 'Reverse Nodes ...",['Linked Lists'],Hard,Reverse Nodes in k-Group,"Given the head of a linked list, reverse the n...","class Solution:\n def reverseKGroup(self, h..."
19,"{'index': 41, 'question name': 'Flatten Binary...","['Linked Lists', 'Binary Search']",Medium,Flatten Binary Tree to Linked List,"Given the root of a binary tree, flatten the t...","class Solution:\n def flatten(self, root: O..."
20,"{'index': 42, 'question name': 'Binary Tree Ma...","['Binary Trees', 'Dynamic Programming', 'DFS']",Hard,Binary Tree Maximum Path Sum,A path in a binary tree is a sequence of nodes...,"class Solution:\n def maxPathSum(self, root..."
21,"{'index': 43, 'question name': 'Binary Tree Ca...","['Dynamic Programming', 'Binary Trees', 'DFS']",Hard,Binary Tree Cameras,You are given the root of a binary tree. We in...,"class Solution:\n def minCameraCover(self, ..."
22,"{'index': 44, 'question name': 'Vertical Order...","['DFS', 'BFS', 'Sorting', 'Binary Trees']",Hard,Vertical Order Traversal of a Binary Tree,"Given the root of a binary tree, calculate the...",class Solution:\n def verticalTraversal(sel...
23,"{'index': 45, 'question name': 'Recover a Tree...","['Binary Trees', 'DFS']",Hard,Recover a Tree from PreOrder Traversal,We run a preorder depth-first search (DFS) on ...,class Solution:\n def recoverFromPreorder(s...

In [10]:
df = pd.read_excel("benchmark_prototype.xlsx")

In [103]:
dataset.to_excel("benchmark_prototype.xlsx")

In [ ]:
result = pd.concat([df , dataset], axis=0)
result = result.iloc[: , 1:]
result.head()

,meta_data,topic,difficulty,question,problem_description,entry_point
0,"{'index': 1, 'question name': 'Jump Game II', ...","['Array', 'Greedy', 'Dynamic Programming']",Medium,Jump Game II,You are given a 0-indexed array of integers nu...,"class Solution:\n def jump(self, nums: List..."
1,"{'index': 2, 'question name': 'Candy', 'diffic...","['Array', 'Greedy']",Hard,Candy,There are n children standing in a line. Each ...,"class Solution:\n def candy(self, ratings: ..."
2,"{'index': 3, 'question name': 'Gas Station', '...","['Array', 'Greedy']",Medium,Gas Station,There are n gas stations along a circular rout...,class Solution:\n def canCompleteCircuit(se...
3,"{'index': 4, 'question name': 'Queue Reconstru...","['Array', 'Binary Trees', 'Sorting']",Medium,Queue Reconstruction by Height,"You are given an array of people, people, whic...",class Solution:\n def reconstructQueue(self...
4,"{'index': 5, 'question name': 'Longest Increas...","['Array', 'Dynamic Programming']",Medium,Longest Increasing Subsequence,"Given an integer array nums, return the length...","class Solution:\n def lengthOfLIS(self, num..."

In [14]:
result.shape[0]

42

In [16]:
result.to_excel("benchmark_prototype_(1).xlsx")